import type { Metadata } from "next";
import { Inter, Josefin_Sans } from "next/font/google";
import { Klee_One } from "next/font/google";
import "./global.css";
import Header from "@/components/ui/Header";

const inter = Inter({ subsets: ["latin"] });
const KleeOneFont = Klee_One({
  weight: "600",
  subsets: ["latin"],
});

const JosefinSans = Josefin_Sans({
  weight: "400",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "PLANTS POST",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={JosefinSans.className}>
        <Header />
        {children}
      </body>
    </html>
  );
}
